---
title: "Analisis_tamanio_sala"
author: "Joaquin Cervino"
date: "2024-05-22"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r dependencies, message=FALSE, warning=FALSE}
library(dplyr)
library(tidyverse)
library(reshape2) # melt
library(rstatix) # stat.test
library(ggplot2)
library(ggthemes)
library(ggpubr)
library(ggstatsplot)
```

## Tamaño de sala

Cómo perciben el tamaño de sala los participantes para el experi 2 y el experi 3


```{r load_data experiment 2, message=FALSE, warning=FALSE}
rm(list=ls())
tabla.exp_2 <- read.csv("../Exp_2_ADP_control/data/tamanio_de_sala_sin_outliers_oscuras_visual.csv", header = TRUE, sep = ' ', stringsAsFactors = TRUE)
tabla.exp_3 <- read.csv("../Exp_3_ADP_vr/data/tamanio_de_sala_sin_outliers_oscuras_virtual.csv", header = TRUE, sep = ' ',
                        stringsAsFactors = TRUE)
```

```{r figures exp 2, message=FALSE, warning=FALSE}
dimensions.volume <- melt(tabla.exp_2, id.vars='nsub',
                          measure.vars=c("OSCURAS_volumen", "VISUAL_volumen"))

dimensions.volume <- dimensions.volume %>%
  mutate(
    variable = case_when(
      variable == "OSCURAS_volumen" ~ "No visual Information",
      variable == "VISUAL_volumen" ~ "Visual Information",
    )
  )

# Voy a remover outliers, valores superior 1000 m3
dimensions.volume <- dimensions.volume %>%
  filter(!value >= 1000)

#dimensions.volume <- dimensions.volume %>%
#  filter(!nsub == 18)

dimensions.volume_aggr <- dimensions.volume %>%
  group_by(variable) %>%
  summarize(
    mean_volume = mean(value),
    sd_volume = sd(value),
    se = sd_volume / sqrt(n())
  )

eqn1 <- sprintf(
  "M = %.3g ± %.4g",
  dimensions.volume_aggr$mean_volume[1],
  dimensions.volume_aggr$se[1])

eqn2 <- sprintf(
  "M = %.3g ± %.4g",
  dimensions.volume_aggr$mean_volume[2],
  dimensions.volume_aggr$se[2])

dimensions.volume <- dimensions.volume %>%
  ungroup()

dimensions.volume <- dimensions.volume %>%
  rename("Volume" = "value",
         "Condition" = "variable")

stat.test <- dimensions.volume  %>% 
  t_test(Volume~Condition, paired=TRUE) %>%
  add_significance()


dim_barchart <- dimensions.volume_aggr %>%
  ggplot(aes(variable, mean_volume)) +
  geom_col(aes(fill = variable), color ="black", width =0.85) +
  geom_errorbar(aes(ymin=mean_volume - se,
                    ymax=mean_volume + se),
                color = "#22292F",
                width = .1) +
  #scale_fill_grey(start = 0.3) +
  #ylim = c(0, 300) +
  scale_y_continuous(limits = c(0, 310), expand = c(0, 0)) +
  geom_hline(yintercept=252,linetype="dashed") +
  annotate("text", x=0.75, y=259, label= expression("252 m"^3*" ")) +
  guides(fill = "none") +
  #theme(legend.position="none") +
  theme_minimal() +
  annotate("text",                        # Add text for mean
           #x = 1.5, # para fig sola
           x = 0.50, # para fig compuesta
           y = 290.0,
           label = eqn1,
           size = 3.25,
           hjust = 0) +
  annotate("text",                        # Add text for mean
           #x = 1.5, # para fig sola
           x = 1.50, # para fig compuesta
           y = 290.0,
           label = eqn2,
           size = 3.25,
           hjust = 0) +
  labs(
    #x = "Condición",
    y = expression("Perceived volume (m"^3*")"),
    #title = "Volumen de sala real vs virtual",
    #caption = "Barra de errores indica desviación estándar"
  )+
  scale_fill_brewer(palette="YlOrRd")+
  theme(#axis.line = element_blank(),
    axis.title.x = element_blank())

# paired <- ggpaired(dimensions.volume, x = "condicion" , y = "volume")
# plot(paired)

stat.test <- stat.test %>% add_xy_position(x = "Condition", fun = "mean", step.increase = 10) # step.increase = 28)

dim_barchart <- dim_barchart + 
  stat_pvalue_manual(stat.test, label = "p", tip.length = 0.05, size = 3, bracket.shorten = 0.1)

# d,w, h comparasion ------------------------------------------------------
#DEPTH
dimensions.depth <- melt(tabla.exp_2, id.vars='nsub',
                          measure.vars=c("OSCURAS_depth", "VISUAL_depth"))

dimensions.depth <- dimensions.depth %>%
  mutate(
    variable = case_when(
      variable == "OSCURAS_depth" ~ "No visual information",
      variable == "VISUAL_depth" ~ "Visual information",
    )
  )
dimensions.depth <- dimensions.depth %>%
  rename("Depth" = "value",
         "Condition" = "variable")

dimensions.depth <- dimensions.depth %>%
  filter(!Depth >= 20)

dimensions.depth_sum <- dimensions.depth %>%
  group_by(Condition) %>%
  summarise(
    mean = mean(Depth),
    median = median(Depth),
    sd = sd(Depth),
    se = sd/sqrt(n())
  )

eqn1 <- sprintf(
  "M = %.3g ± %.2g \nMdn = %.3g",
  dimensions.depth_sum$mean[1],
  dimensions.depth_sum$se[1],
  dimensions.depth_sum$median[1])

eqn2 <- sprintf(
  "M = %.3g ± %.2g \nMdn = %.3g",
  dimensions.depth_sum$mean[2],
  dimensions.depth_sum$se[2],
  dimensions.depth_sum$median[2])

# Use single color
violin_depth <- ggplot(dimensions.depth, aes(x=Condition, y=Depth,  fill=Condition)) +
  geom_violin(trim=FALSE) +
  #geom_boxplot(width=0.1) +
  geom_errorbar(data= dimensions.depth_sum, mapping = aes(y= mean , ymin=mean - se,
      ymax=mean + se),
      color = "#22292F",
      width = .1) +
  geom_jitter(alpha = 0.1) +
  annotate("text",                        # Add text for mean
           #x = 1.5, # para fig sola
           x = 0.450, # para fig compuesta
           y = 18.0,
           label = eqn1,
           size = 2.35,
           hjust = 0) +
  annotate("text",                        # Add text for mean
           #x = 1.5, # para fig sola
           x = 1.4, # para fig compuesta
           y = 18.0,
           label = eqn2,
           size = 2.35,
           hjust = 0) +
  labs(
    y = "Depth (m)",
  )+
  theme_minimal() +
  guides(fill = "none") +
  scale_fill_brewer(palette="YlOrRd")+
  #geom_dotplot(binaxis='y', stackdir='center', dotsize=1) +
  geom_hline(yintercept=12,linetype="dashed") +
  annotate("text", x=0.5, y=10, label= "12 m", size=2.5) +
  theme(
    axis.text.x=element_blank(),
    axis.title.x = element_blank(),
    axis.title.y = element_text(hjust = 0)) 

# ANCHO 

dimensions.width <- melt(tabla.exp_2, id.vars='nsub',
                         measure.vars=c("OSCURAS_width", "VISUAL_width"))

dimensions.width <- dimensions.width %>%
  mutate(
    variable = case_when(
      variable == "OSCURAS_width" ~ "No Visual information",
      variable == "VISUAL_width" ~ "Visual information",
    )
  )

dimensions.width <- dimensions.width %>%
  rename("Width" = "value",
         "Condition" = "variable")

dimensions.width <- dimensions.width %>%
  filter(!Width >= 10)

dimensions.width_sum <- dimensions.width %>%
  group_by(Condition) %>%
  summarise(
    mean = mean(Width),
    median = median(Width),
    sd = sd(Width),
    se = sd / sqrt(n())
  )

eqn1 <- sprintf(
  "M = %.3g ± %.2g \nMdn = %.3g",
  dimensions.width_sum$mean[1],
  dimensions.width_sum$se[1],
  dimensions.width_sum$median[1])

eqn2 <- sprintf(
  "M = %.3g ± %.2g \nMdn = %.3g",
  dimensions.width_sum$mean[2],
  dimensions.width_sum$se[2],
  dimensions.width_sum$median[2])

# Use single color
violin_width <- ggplot(dimensions.width, aes(x=Condition, y=Width,  fill=Condition)) +
  #geom_violin(trim=FALSE, fill='#A4A4A4', color="darkred")+
  geom_violin(trim=FALSE)+
  geom_errorbar(data= dimensions.width_sum, mapping = aes(y= mean , ymin=mean - se,
      ymax=mean + se),
      color = "#22292F",
      width = .1) +
  geom_jitter(alpha = 0.1) +
  # geom_text(data = dimensions.width_sum, aes(x = Condición, y = mean, 
  #   label = paste("Mean: ", round(mean, 1), "\nMedian: ", median, "\nSD: ", round(sd, 1)),
  #   hjust=0, position = ,
  # ))+
  annotate("text",                        # Add text for mean
           #x = 1.5, # para fig sola
           x = 0.50, # para fig compuesta
           y = 8.0,
           label = eqn1,
           size = 2.35,
           hjust = 0) +
  annotate("text",                        # Add text for mean
           #x = 1.5, # para fig sola
           x = 1.40, # para fig compuesta
           y = 8.0,
           label = eqn2,
           size = 2.35,
           hjust = 0) +
  theme_minimal() +
  guides(fill = "none") +
  scale_fill_brewer(palette="YlOrRd")+
  #geom_dotplot(binaxis='y', stackdir='center', dotsize=1) +
  geom_hline(yintercept=7,linetype="dashed")+
  annotate("text", x=0.5, y=6, label= "7 m", size=2.5) +
  labs(
    y = "Width (m)",
  ) +
  theme(
    axis.title.x = element_blank(),
    axis.text.x=element_blank()) 

# ALTO

dimensions.height <- melt(tabla.exp_2, id.vars='nsub',
                          measure.vars=c("OSCURAS_height", "VISUAL_height"))

dimensions.height <- dimensions.height %>%
  mutate(
    variable = case_when(
      variable == "OSCURAS_height" ~ "No visual information",
      variable == "VISUAL_height" ~ "Visual information",
    )
  )

dimensions.height <- dimensions.height %>%
  rename("Height" = "value",
         "Condition" = "variable")

dimensions.height <- dimensions.height %>%
  filter(!Height >= 6)

dimensions.height_sum <- dimensions.height %>%
  group_by(Condition) %>%
  summarise(
    mean = mean(Height),
    median = median(Height),
    sd = sd(Height),
    se = sd / sqrt(n())
  )

eqn1 <- sprintf(
  "M = %.3g ± %.2g \nMdn = %.3g",
  dimensions.height_sum$mean[1],
  dimensions.height_sum$se[1],
  dimensions.height_sum$median[1])

eqn2 <- sprintf(
  "M = %.3g ± %.2g \nMdn = %.3g",
  dimensions.height_sum$mean[2],
  dimensions.height_sum$se[2],
  dimensions.height_sum$median[2])

# Use single color
violin_height <- ggplot(dimensions.height, aes(x=Condition, y=Height,  fill=Condition)) +
  geom_violin(trim=FALSE)+
  geom_errorbar(data= dimensions.height_sum, mapping = aes(y= mean , ymin=mean - se,
      ymax=mean + se),
      color = "#22292F",
      width = .1) +
  geom_jitter(alpha = 0.1) +
  annotate("text",                        # Add text for mean
           #x = 1.5, # para fig sola
           x = 0.50, # para fig compuesta
           y = 4.9,
           label = eqn1,
           size = 2.35,
           hjust = 0) +
  annotate("text",                        # Add text for mean
           #x = 1.5, # para fig sola
           x = 1.40, # para fig compuesta
           y = 4.9,
           label = eqn2,
           size = 2.35,
           hjust = 0) +
  theme_minimal() +
  guides(fill = "none") +
  scale_fill_brewer(palette="YlOrRd")+
  #geom_dotplot(binaxis='y', stackdir='center', dotsize=1) +
  geom_hline(yintercept=3,linetype="dashed") +
  annotate("text", x=0.5, y=2.5, label= "3 m", size=2.5) +
  labs(
    y = "Height (m)",
  ) +
  theme(
    axis.title.x = element_blank()) 

#plot(violin_height)


# figure <- ggarrange(violin_depth, violin_width,violin_height,
#                     ncol = 3, labels = c("B", "C", "D"))

figure <- ggarrange(dim_barchart, 
                    ggarrange(violin_depth, violin_width,violin_height, widths = c(1.5,2),
                              nrow = 3, labels = c("B", "C", "D")),
                    ncol = 2, 
                    labels ="A",
                    heights = c(1, 0.75))
#figure

figures_folder = "./figuras"
mi_nombre_de_archivo = paste(figures_folder, .Platform$file.sep, "Perceived_room_OSCURAS_VISUAL_2.png", sep = '')
ggsave(mi_nombre_de_archivo, plot =figure, width = 1400, height=1000, dpi=200, units = "px")
```

```{r figures exp 3, message=FALSE, warning=FALSE}
dimensions.volume <- melt(tabla.exp_3, id.vars='nsub',
                          measure.vars=c("OSCURAS_volumen", "VIRTUAL_volumen"))

dimensions.volume <- dimensions.volume %>%
  mutate(
    variable = case_when(
      variable == "OSCURAS_volumen" ~ "No visual Information",
      variable == "VIRTUAL_volumen" ~ "Virtual Environment",
    )
  )

# Voy a remover outliers, valores superior 1000 m3
dimensions.volume <- dimensions.volume %>%
  filter(!value >= 1000)

#dimensions.volume <- dimensions.volume %>%
#  filter(!nsub == 18)

dimensions.volume_aggr <- dimensions.volume %>%
  group_by(variable) %>%
  summarize(
    mean_volume = mean(value),
    sd_volume = sd(value),
    se = sd_volume / sqrt(n())
  )

eqn1 <- sprintf(
  "M = %.3g ± %.4g",
  dimensions.volume_aggr$mean_volume[1],
  dimensions.volume_aggr$se[1])

eqn2 <- sprintf(
  "M = %.3g ± %.4g",
  dimensions.volume_aggr$mean_volume[2],
  dimensions.volume_aggr$se[2])

dimensions.volume <- dimensions.volume %>%
  ungroup()

dimensions.volume <- dimensions.volume %>%
  rename("Volume" = "value",
         "Condition" = "variable")

stat.test <- dimensions.volume  %>% 
  t_test(Volume~Condition, paired=FALSE) %>%
  add_significance()


dim_barchart <- dimensions.volume_aggr %>%
  ggplot(aes(variable, mean_volume)) +
  geom_col(aes(fill = variable), color ="black", width =0.85) +
  geom_errorbar(aes(ymin=mean_volume - se,
                    ymax=mean_volume + se),
                color = "#22292F",
                width = .1) +
  #scale_fill_grey(start = 0.3) +
  #ylim = c(0, 300) +
  scale_y_continuous(limits = c(0, 310), expand = c(0, 0)) +
  geom_hline(yintercept=252,linetype="dashed") +
  annotate("text", x=0.75, y=259, label= expression("252 m"^3*" ")) +
  guides(fill = "none") +
  #theme(legend.position="none") +
  theme_minimal() +
  annotate("text",                        # Add text for mean
           #x = 1.5, # para fig sola
           x = 0.50, # para fig compuesta
           y = 290.0,
           label = eqn1,
           size = 3.25,
           hjust = 0) +
  annotate("text",                        # Add text for mean
           #x = 1.5, # para fig sola
           x = 1.50, # para fig compuesta
           y = 290.0,
           label = eqn2,
           size = 3.25,
           hjust = 0) +
  labs(
    #x = "Condición",j
    y = expression("Perceived volume (m"^3*")"),
    #title = "Volumen de sala real vs virtual",
    #caption = "Barra de errores indica desviación estándar"
  )+
  scale_fill_brewer(palette="YlOrRd")+
  theme(#axis.line = element_blank(),
    axis.title.x = element_blank())

# paired <- ggpaired(dimensions.volume, x = "condicion" , y = "volume")
# plot(paired)

stat.test <- stat.test %>% add_xy_position(x = "Condition", fun = "mean", step.increase = 10) # step.increase = 28)

dim_barchart <- dim_barchart + 
  stat_pvalue_manual(stat.test, label = "p", tip.length = 0.05, size = 3, bracket.shorten = 0.1)

# d,w, h comparasion ------------------------------------------------------
#DEPTH
dimensions.depth <- melt(tabla.exp_3, id.vars='nsub',
                          measure.vars=c("OSCURAS_depth", "VIRTUAL_depth"))

dimensions.depth <- dimensions.depth %>%
  mutate(
    variable = case_when(
      variable == "OSCURAS_depth" ~ "No visual information",
      variable == "VIRTUAL_depth" ~ "Virtual environment",
    )
  )
dimensions.depth <- dimensions.depth %>%
  rename("Depth" = "value",
         "Condition" = "variable")

dimensions.depth <- dimensions.depth %>%
  filter(!Depth >= 20)

dimensions.depth_sum <- dimensions.depth %>%
  group_by(Condition) %>%
  summarise(
    mean = mean(Depth),
    median = median(Depth),
    sd = sd(Depth),
    se = sd / sqrt(n())
  )

eqn1 <- sprintf(
  "M = %.3g ± %.2g \nMdn = %.3g",
  dimensions.depth_sum$mean[1],
  dimensions.depth_sum$se[1],
  dimensions.depth_sum$median[1])

eqn2 <- sprintf(
  "M = %.3g ± %.2g \nMdn = %.3g",
  dimensions.depth_sum$mean[2],
  dimensions.depth_sum$se[2],
  dimensions.depth_sum$median[2])

# Use single color
violin_depth <- ggplot(dimensions.depth, aes(x=Condition, y=Depth,  fill=Condition)) +
  geom_violin(trim=FALSE) +
  geom_errorbar(data= dimensions.depth_sum, mapping = aes(y= mean , ymin=mean - se,
          ymax=mean + se),
          color = "#22292F",
          width = .1) +
  geom_jitter(alpha = 0.1) +
  annotate("text",                        # Add text for mean
           #x = 1.5, # para fig sola
           x = 0.450, # para fig compuesta
           y = 12.5,
           label = eqn1,
           size = 2.35,
           hjust = 0) +
  annotate("text",                        # Add text for mean
           #x = 1.5, # para fig sola
           x = 1.4, # para fig compuesta
           y = 12.5,
           label = eqn2,
           size = 2.35,
           hjust = 0) +
  labs(
    y = "Depth (m)",
  )+
  theme_minimal() +
  guides(fill = "none") +
  scale_fill_brewer(palette="YlOrRd")+
  #geom_dotplot(binaxis='y', stackdir='center', dotsize=1) +
  geom_hline(yintercept=12,linetype="dashed") +
  annotate("text", x=0.5, y=10, label= "12 m", size=2.5) +
  theme(
    axis.text.x = element_blank(),
    axis.title.x = element_blank(),
    axis.title.y = element_text(hjust = 0)) 

# ANCHO 

dimensions.width <- melt(tabla.exp_3, id.vars='nsub',
                         measure.vars=c("OSCURAS_width", "VIRTUAL_width"))

dimensions.width <- dimensions.width %>%
  mutate(
    variable = case_when(
      variable == "OSCURAS_width" ~ "No Visual information",
      variable == "VIRTUAL_width" ~ "Virtual environment",
    )
  )

dimensions.width <- dimensions.width %>%
  rename("Width" = "value",
         "Condition" = "variable")

dimensions.width <- dimensions.width %>%
  filter(!Width >= 10)

dimensions.width_sum <- dimensions.width %>%
  group_by(Condition) %>%
  summarise(
    mean = mean(Width),
    median = median(Width),
    sd = sd(Width),
    se = sd / sqrt(n())
  )

eqn1 <- sprintf(
  "M = %.3g ± %.2g \nMdn = %.3g",
  dimensions.width_sum$mean[1],
  dimensions.width_sum$se[1],
  dimensions.width_sum$median[1])

eqn2 <- sprintf(
  "M = %.3g ± %.2g \nMdn = %.3g",
  dimensions.width_sum$mean[2],
  dimensions.width_sum$se[2],
  dimensions.width_sum$median[2])

# Use single color
violin_width <- ggplot(dimensions.width, aes(x=Condition, y=Width,  fill=Condition)) +
  #geom_violin(trim=FALSE, fill='#A4A4A4', color="darkred")+
  geom_violin(trim=FALSE)+
  geom_errorbar(data= dimensions.width_sum, mapping = aes(y= mean , ymin=mean - se,
    ymax=mean + se),
    color = "#22292F",
    width = .1) +
  geom_jitter(alpha = 0.1) +
  annotate("text",                        # Add text for mean
           #x = 1.5, # para fig sola
           x = 0.50, # para fig compuesta
           y = 8.0,
           label = eqn1,
           size = 2.35,
           hjust = 0) +
  annotate("text",                        # Add text for mean
           #x = 1.5, # para fig sola
           x = 1.40, # para fig compuesta
           y = 8.0,
           label = eqn2,
           size = 2.35,
           hjust = 0) +
  theme_minimal() +
  guides(fill = "none") +
  scale_fill_brewer(palette="YlOrRd")+
  #geom_dotplot(binaxis='y', stackdir='center', dotsize=1) +
  geom_hline(yintercept=7,linetype="dashed")+
  annotate("text", x=0.5, y=6, label= "7 m", size=2.5) +
  labs(
    y = "Width (m)",
  ) +
  theme(
    axis.text.x= element_blank(),
    axis.title.x = element_blank()) 

# ALTO

dimensions.height <- melt(tabla.exp_3, id.vars='nsub',
                          measure.vars=c("OSCURAS_height", "VIRTUAL_height"))

dimensions.height <- dimensions.height %>%
  mutate(
    variable = case_when(
      variable == "OSCURAS_height" ~ "No visual information",
      variable == "VIRTUAL_height" ~ "Virtual environment",
    )
  )

dimensions.height <- dimensions.height %>%
  rename("Height" = "value",
         "Condition" = "variable")

dimensions.height <- dimensions.height %>%
  filter(!Height >= 6)

dimensions.height_sum <- dimensions.height %>%
  group_by(Condition) %>%
  summarise(
    mean = mean(Height),
    median = median(Height),
    sd = sd(Height),
    se  = sd / sqrt(n())
  )

eqn1 <- sprintf(
  "M = %.3g ± %.2g \nMdn = %.3g",
  dimensions.height_sum$mean[1],
  dimensions.height_sum$se[1],
  dimensions.height_sum$median[1])

eqn2 <- sprintf(
  "M = %.3g ± %.2g \nMdn = %.3g",
  dimensions.height_sum$mean[2],
  dimensions.height_sum$se[2],
  dimensions.height_sum$median[2])

# Use single color
violin_height <- ggplot(dimensions.height, aes(x=Condition, y=Height,  fill=Condition)) +
  geom_violin(trim=FALSE)+
  geom_errorbar(data= dimensions.height_sum, mapping = aes(y= mean , ymin=mean - se,
      ymax=mean + se),
      color = "#22292F",
      width = .1) +  
  geom_jitter(alpha = 0.1) +
  annotate("text",                        # Add text for mean
           #x = 1.5, # para fig sola
           x = 0.50, # para fig compuesta
           y = 5.75,
           label = eqn1,
           size = 2.35,
           hjust = 0) +
  annotate("text",                        # Add text for mean
           #x = 1.5, # para fig sola
           x = 1.40, # para fig compuesta
           y = 5.75,
           label = eqn2,
           size = 2.35,
           hjust = 0) +
  theme_minimal() +
  guides(fill = "none") +
  scale_fill_brewer(palette="YlOrRd")+
  #geom_dotplot(binaxis='y', stackdir='center', dotsize=1) +
  geom_hline(yintercept=3,linetype="dashed") +
  annotate("text", x=0.5, y=2.5, label= "3 m", size=2.5) +
  labs(
    y = "Height (m)",
  ) +
  theme(
    axis.title.x = element_blank()) 

#plot(violin_height)


# figure <- ggarrange(violin_depth, violin_width,violin_height,
#                     ncol = 3, labels = c("B", "C", "D"))

figure <- ggarrange(dim_barchart, 
                    ggarrange(violin_depth, violin_width,violin_height, widths = c(1.5,2),
                              nrow = 3, labels = c("B", "C", "D")),
                    ncol = 2, 
                    labels ="A",
                    heights = c(1, 0.75))
#figure

figures_folder = "./figuras"
mi_nombre_de_archivo = paste(figures_folder, .Platform$file.sep, "Perceived_room_OSCURAS_VIRTUAL_2.png", sep = '')
ggsave(mi_nombre_de_archivo, plot =figure, width = 1400, height=1000, dpi=200, units = "px")
```