---
title: "Analisis_tamanio_sala"
author: "Joaquin Cervino"
date: "2024-05-22"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r dependencies, message=FALSE, warning=FALSE}
library(dplyr)
library(tidyverse)
library(reshape2) # melt
library(rstatix) # stat.test
library(ggplot2)
library(ggthemes)
library(ggpubr)
library(ggstatsplot)
```

## Tamaño de sala

Cómo perciben el tamaño de sala los participantes para el experi 2 y el experi 3


```{r load_data experiment 2, message=FALSE, warning=FALSE}
rm(list=ls())

tabla.exp_3 <- read.csv("../Exp_3_ADP_vr/data/tamanio_de_sala_sin_outliers_oscuras_virtual.csv", header = TRUE, sep = ' ',
                        stringsAsFactors = TRUE)
```


```{r figures exp 3, message=FALSE, warning=FALSE}



# d,w, h comparasion ------------------------------------------------------
#DEPTH
# melt ya fue
#dimensions.depth <- melt(tabla.exp_3, id.vars='Subject',
#                          measure.vars=c("No_visual_info_depth", "VE_depth"))
dimensions.depth <- tabla.exp_1 %>%
  pivot_longer(cols = c("SC_RV_depth", "SG_RV_depth", "SR_depth"),
               names_to = "variable",
               values_to = "value")



dimensions.depth <- dimensions.depth %>%
  mutate(
    variable = case_when(
      variable == "No_visual_info_depth" ~ "No visual information",
      variable == "VE_depth" ~ "Virtual environment",
    )
  )
dimensions.depth <- dimensions.depth %>%
  rename("Depth" = "value",
         "Condition" = "variable")

dimensions.depth <- dimensions.depth %>%
  filter(!Depth >= 20)

dimensions.depth_sum <- dimensions.depth %>%
  group_by(Condition) %>%
  summarise(
    mean = mean(Depth),
    median = median(Depth),
    sd = sd(Depth),
    se = sd / sqrt(n())
  )
# antes era asi, con mediana
#eqn1 <- sprintf(
#  "M = %.3g ± %.2g \nMdn = %.3g",
#  dimensions.depth_sum$mean[1],
#  dimensions.depth_sum$se[1],
#  dimensions.depth_sum$median[1])

eqn1 <- sprintf(
  "M = %.3g \n ± %.2g",
  dimensions.depth_sum$mean[1],
  dimensions.depth_sum$se[1])

eqn2 <- sprintf(
  "M = %.3g \n ± %.2g",
  dimensions.depth_sum$mean[2],
  dimensions.depth_sum$se[2])

t_test_depth <- t.test(Depth~Condition, data= dimensions.depth)

# Use single color
violin_depth <- ggplot(dimensions.depth, aes(x=Condition, y=Depth,  fill=Condition)) +
  geom_violin(trim=FALSE) +
  geom_errorbar(data= dimensions.depth_sum, mapping = aes(y= mean , ymin=mean - se,
          ymax=mean + se),
          color = "#22292F",
          width = .1) +
  geom_jitter(alpha = 0.1) +
  annotate("text",                        # Add text for mean
           #x = 1.5, # para fig sola
           x = 0.450, # para fig compuesta
           y = 15.5,
           label = eqn1,
           size = 2.35,
           hjust = 0) +
  annotate("text",                        # Add text for mean
           #x = 1.5, # para fig sola
           x = 1.4, # para fig compuesta
           y = 15.5,
           label = eqn2,
           size = 2.35,
           hjust = 0) +
    labs(
    y = "Depth (m)",
  )+
  theme_minimal() +
  guides(fill = "none") +
  scale_fill_brewer(palette="YlOrRd")+
  #geom_dotplot(binaxis='y', stackdir='center', dotsize=1) +
  geom_hline(yintercept=12,linetype="dashed") +
  annotate("text", x=0.5, y=10, label= "12 m", size=2.5) +
  theme(
    axis.text.x = element_blank(),
    axis.title.x = element_blank(),
    axis.title.y = element_text(hjust = 0)) 

# ANCHO 

dimensions.width <- melt(tabla.exp_3, id.vars='Subject',
                         measure.vars=c("No_visual_info_width", "VE_width"))

dimensions.width <- dimensions.width %>%
  mutate(
    variable = case_when(
      variable == "No_visual_info_width" ~ "No Visual information",
      variable == "VE_width" ~ "Virtual environment",
    )
  )

dimensions.width <- dimensions.width %>%
  rename("Width" = "value",
         "Condition" = "variable")

dimensions.width <- dimensions.width %>%
  filter(!Width >= 10)

dimensions.width_sum <- dimensions.width %>%
  group_by(Condition) %>%
  summarise(
    mean = mean(Width),
    median = median(Width),
    sd = sd(Width),
    se = sd / sqrt(n())
  )

eqn1 <- sprintf(
  "M = %.3g \n ± %.2g",
  dimensions.width_sum$mean[1],
  dimensions.width_sum$se[1])

eqn2 <- sprintf(
  "M = %.3g \n  ± %.2g",
  dimensions.width_sum$mean[2],
  dimensions.width_sum$se[2])

t_test_width <- t.test(Width~Condition, data= dimensions.width)
# Use single color
violin_width <- ggplot(dimensions.width, aes(x=Condition, y=Width,  fill=Condition)) +
  #geom_violin(trim=FALSE, fill='#A4A4A4', color="darkred")+
  geom_violin(trim=FALSE)+
  geom_errorbar(data= dimensions.width_sum, mapping = aes(y= mean , ymin=mean - se,
    ymax=mean + se),
    color = "#22292F",
    width = .1) +
  geom_jitter(alpha = 0.1) +
  annotate("text",                        # Add text for mean
           #x = 1.5, # para fig sola
           x = 0.50, # para fig compuesta
           y = 9.0,
           label = eqn1,
           size = 2.35,
           hjust = 0) +
  annotate("text",                        # Add text for mean
           #x = 1.5, # para fig sola
           x = 1.40, # para fig compuesta
           y = 9.0,
           label = eqn2,
           size = 2.35,
           hjust = 0) +
  geom_signif(comparisons = list(c("No visual information",
                                 "Visual information")),   
            map_signif_level=TRUE,
            tip_length = 0.0, 
            size = 0.5,
            y_position = 13,
            extend_line = -0.4)+
  theme_minimal() +
  guides(fill = "none") +
  scale_fill_brewer(palette="YlOrRd")+
  #geom_dotplot(binaxis='y', stackdir='center', dotsize=1) +
  geom_hline(yintercept=7,linetype="dashed")+
  annotate("text", x=0.5, y=6, label= "7 m", size=2.5) +
  labs(
    y = "Width (m)",
  ) +
  theme(
    axis.text.x= element_blank(),
    axis.title.x = element_blank()) 

# ALTO

dimensions.height <- melt(tabla.exp_3, id.vars='Subject',
                          measure.vars=c("No_visual_info_height", "VE_height"))

dimensions.height <- dimensions.height %>%
  mutate(
    variable = case_when(
      variable == "No_visual_info_height" ~ "No visual information",
      variable == "VE_height" ~ "Virtual environment",
    )
  )

dimensions.height <- dimensions.height %>%
  rename("Height" = "value",
         "Condition" = "variable")

dimensions.height <- dimensions.height %>%
  filter(!Height >= 6)

dimensions.height_sum <- dimensions.height %>%
  group_by(Condition) %>%
  summarise(
    mean = mean(Height),
    median = median(Height),
    sd = sd(Height),
    se  = sd / sqrt(n())
  )

eqn1 <- sprintf(
  "M = %.3g \n ± %.2g",
  dimensions.height_sum$mean[1],
  dimensions.height_sum$se[1])

eqn2 <- sprintf(
  "M = %.3g \n ± %.2g",
  dimensions.height_sum$mean[2],
  dimensions.height_sum$se[2])


t_test_height <- t.test(Height~Condition, data= dimensions.height)
# Use single color
violin_height <- ggplot(dimensions.height, aes(x=Condition, y=Height,  fill=Condition)) +
  geom_violin(trim=FALSE)+
  geom_errorbar(data= dimensions.height_sum, mapping = aes(y= mean , ymin=mean - se,
      ymax=mean + se),
      color = "#22292F",
      width = .1) +  
  geom_jitter(alpha = 0.1) +
  annotate("text",                        # Add text for mean
           #x = 1.5, # para fig sola
           x = 0.50, # para fig compuesta
           y = 5.75,
           label = eqn1,
           size = 2.35,
           hjust = 0) +
  annotate("text",                        # Add text for mean
           #x = 1.5, # para fig sola
           x = 1.40, # para fig compuesta
           y = 5.75,
           label = eqn2,
           size = 2.35,
           hjust = 0) +
  theme_minimal() +
  guides(fill = "none") +
  scale_fill_brewer(palette="YlOrRd")+
  #geom_dotplot(binaxis='y', stackdir='center', dotsize=1) +
  geom_hline(yintercept=3,linetype="dashed") +
  annotate("text", x=0.5, y=2.5, label= "3 m", size=2.5) +
  labs(
    y = "Height (m)",
  ) +
  theme(
    axis.title.x = element_blank()) 

#plot(violin_height)


# figure <- ggarrange(violin_depth, violin_width,violin_height,
#                     ncol = 3, labels = c("B", "C", "D"))

figure <- ggarrange(dim_barchart, 
                    ggarrange(violin_depth, violin_width,violin_height, widths = c(1.5,2),
                              nrow = 3, labels = c("B", "C", "D")),
                    ncol = 2, 
                    labels ="A",
                    heights = c(1, 0.75))
#figure

figures_folder = "./figuras"
mi_nombre_de_archivo = paste(figures_folder, .Platform$file.sep, "Perceived_room_OSCURAS_VIRTUAL_2.png", sep = '')
ggsave(mi_nombre_de_archivo, plot =figure, width = 1400, height=1000, dpi=200, units = "px")
```